import { Navigation } from "@components/Navigation";
import "@styles/globals.css";
import type { Metadata } from "next";
import { Aleo, Manrope, Nunito } from "next/font/google";

const aleo = Aleo({
  subsets: ["latin-ext"],
  display: "auto",
  variable: "--font-aleo",
});
const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-mr",
});

const nunito = Nunito({
  subsets: ["cyrillic"],
  variable: "--font-raleway",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${nunito.variable} ${aleo.variable}`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
